### ISSUE TITLE
Symbol IACA always defined in include/clmul.h

### ISSUE THREAD

**Issue by WojciechMula** [lemire/StronglyUniversalStringHashing#1]
Please allow to set this symbol via make options and also set the path to IACA, as it's also hardwired in the code.

Since I haven't IACA installed, I removed the definition and was able to compile (GCC 4.9.2) and run test programs.

**Comment by lemire** [comment]
I will. Thanks for the feedback.

**Comment by lemire** [comment]
Ok. IACA references have been pruned out.

I am closing this, re-open if you disagree.

**Comment by lemire** [comment]
BTW, looking at your personal web site, I think you might enjoy these papers if you have never checked them out:

http://arxiv.org/abs/1401.6399

http://arxiv.org/abs/1502.01916

**Comment by WojciechMula** [comment]
Thank you for prompt reply and the fix.

Regarding papers I know them, I read your blog, so I'm up to date. You're doing great work, thanks.
