### ISSUE TITLE
Handling messages of length i*1024+j for i >= 2, j in [1-7]

### ISSUE THREAD

**Issue by medsec** [lemire/StronglyUniversalStringHashing#2]
It seems that messages with at least two full 1024-byte blocks and only 1-7 remaining bytes are treated independently of their trailing 1-7 bytes. If confirmed, this would allow to construct trivial collisions for messages of length 2049-2055 bytes that all collide; the same would apply for messages of length 3073-3079, 4097-4103, ... bytes.

The reasons seem to be Line 260 in clmulhierarchical64bits.h, which should use not the floored length.
247    size_t length = lengthbyte / sizeof(uint64_t);
...
260    const int remain = length - t;
261  
262    if (remain != 0) {

**Comment by lemire** [comment]
Thanks. I think that @owenkaser  has been looking at this issue.

**Comment by lemire** [comment]
Seems like the bug was verified. We have a potential fix. We shall do some internal checks before pushing it.

**Comment by lemire** [comment]
@medsec  

You were correct. Our code was buggy in one "rare" case where it would not take into account all input bytes. I have committed @owenkaser 's fix today:

https://github.com/lemire/StronglyUniversalStringHashing/commit/255b2862f1d0a1bd49b5641883223604b0007a69

Closing. Reopen if you disagree.

**Comment by medsec** [comment]
Yes, seems to be successfully fixed. But I had mistaken the printf formats in the quick collision test in the clmulunit.c It should be %lu and %016lx instead of %llu and %016llx. I get a warning by gcc currently. :+1:

**Comment by lemire** [comment]
@medsec 

As I recall, in your original version, you printed out 4-byte integers. I modified it in a non-standard way. It is no good as you point out.

I think that this is the correct way to do it 

https://github.com/lemire/StronglyUniversalStringHashing/commit/d90b77cfd1705e7ee9ddcfd754b1ec8c368e8037
