### ISSUE TITLE
Does the polynomial and inner-product hash miss for messages of 1025-1031 bytes?

### ISSUE THREAD

**Issue by medsec** [lemire/StronglyUniversalStringHashing#3]
The arxiv version points out that messages starting from 1025 bytes length undergo an additional polynomial-hashing and inner-product hashing stage. This is denoted by the else in in Algorithm 4, p.10 in http://arxiv.org/abs/1503.03465. 

Though, function CLHASHbyte in clmulhierarchical64bits.h lets messages between 1025-1031 byte also follow the else path for short strings:

size_t length = lengthbyte / sizeof(uint64_t);

const uint64_t \* string = (const uint64_t *)  stringbyte;
if (m < length) { // long strings, with polynomial and inner-product hash
...
} else { // short strings, no polynomial and inner-product hash
...
}

To me, this is correct in your paper, but misses in the implementation. Do I mistake something here?

**Comment by lemire** [comment]
@medsec 

You are quite correct, I am afraid.

Fixed by this commit :
https://github.com/lemire/StronglyUniversalStringHashing/commit/d32ccaa52107bf9ed8754f808f991b4b73c557ef

Thanks again!

Closing, reopen if you disagree.
